[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ta_py_framework"
version = "0.2.0"
dependencies = [
    "pytest",
    "requests",
    "selenium>=4.7.0",          # Add selenium version
    "webdriver-manager>=3.8.5"   # Add webdriver manager for managing browser drivers
]
